default: &default
  adapter: postgresql
  encoding: unicode
  #host: db
  #username: postgres
  #password: <%= ENV['POSTGRESQL_DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cr4g_development


test:
  <<: *default
  database: cr4g_test

production:
  <<: *default
  username: cr4g
  password: <%= ENV['POSTGRESQL_DATABASE_PASSWORD'] %>
